theupdateframework/go-tuf

README.md, repo.go, repo_test.go, tuf/main.go, tuf/root_keys.go
The client will need the root keys when performing the initial update, so this change helps the maintainer distribute those keys.
=> Add root-keys command

data/types.go, errors.go, repo.go, repo_test.go, tuf/add.go, tuf/gen_key.go, tuf/main.go, tuf/remove.go, tuf/snapshot.go, tuf/timestamp.go
This will help testing indefinite freeze attacks in the client.
Closes #9.
=> Support setting manifest expires via the CLI

client/client.go, client/client_test.go, client/errors.go
This makes it more explicit that the method is downloading potentially unsafe data.
=> client: Add downloadMetaUnsafe

data/types.go, repo.go, repo_test.go
See [commit message](https://github.com/flynn/go-tuf/commit/a38f45cc7924700ce732ebefbaf86db0b9d20ecf) for explanation of removing the version check in `verifySignature`, and I have opened #37 to track fixing version checking when committing changes.
=> Bump metadata versions on change

encrypted/encrypted.go
encrypted.go:103: struct field encrypted has json tag but is not exported
=> encrypted: Fix go vet complaint about json tagged field

client/interop_test.go
If a PYTHONPATH already exists in the environment, it will be used instead of the one we specify, breaking the tests.
=> client: Remove PYTHONPATH from the env before running interop test

data/types.go
This allows consumers of the type to decode into any type instead of being stuck with a `map[string]interface{}`.
=> data: Change FileMeta.Custom from map[string]interface{} to json.RawMessage

client/client.go, client/client_test.go
Closes #39
Version downgrade attack during this scenario is not tested, as it is very unlikely (it would require intentionally signing a metadata file with the wrong version, which makes no sense). The version decode step was verified manually, as it would be very tricky to test (if you have a simple way of testing, suggestions welcome).
=> client: Handle updating root with keys that do not match the local meta

repo.go, repo_test.go, tuf/main.go
When adding all staged targets, `WalkStagedTargets` calls the `targetsFn` with a path relative to the staged targets dir, so we need to normalize the path.
=> repo: Ensure target paths are always normalized

client/remote_store.go
There is no situation where an empty targets path makes sense, so it should default to `"targets"`.
=> client: Add default targets path

util/util.go
This avoids using the wrong slash on Windows.
=> util: Use path instead of filepath for NormalizePath

util/util.go
filepath is incorrect here, as we should always use forward slashes, even on Windows.
=> util: Use path instead of filepath in HashedPaths

cmd/tuf/clean.go, errors.go, local_store.go, repo_test.go
After creating keys in a new repository, `repo.Clean()` would remove the staged `root.json`, rendering the keys unusable.
Given `Clean` is only useful to reset the state to what is committed, it only makes sense to call it when something has been committed already, so this change prevents cleaning a new repository.
Fixes #78.
=> repo: Prevent cleaning a new repository

util/util.go
`path.Join("/", foo)` will always add a `/` on the front of `foo` and additionally a `path.Clean` happens internally as part of `path.Join`
=> simpler NormalizeTargets

signed/verifiers.go, signed/verify.go
There needs to be an update to the keys.Key type to fully support other algorithms. Happy to make those changes if you can provide an opinion. On my fork I just generically treat all keys and signatures as `[]byte` and allow the creators/verifiers to worry about precisely what the correct sizes are and copy the slices into arrays.
Signed-off-by: David Lawrence <david.lawrence@docker.com> (github: endophage)
=> Pluggable verifiers

repo.go, repo_test.go
If I do the following:
```
tuf add --custom '{"foo":"bar"}' foo.txt
tuf add bar.txt
tuf add
```
I expect foo.txt to keep the metadata I give it, but that doesn't currently happen as `tuf add` will set metadata of all staged files to nil.
I have updated the logic to maintain custom metadata if the user hasn't specified any.
=> Don't reset custom metadata when not specified

client/local_store.go
These slices are backed by a mmap’ed memory area and can cause segfaults if not copied out.
/cc @benbjohnson
=> Ensure we copy boltdb values

client/client.go, client/client_test.go
If the local root is expired, an update will download the latest root from remote storage, and we need to be able to verify that new root with the local keys.
We should probably add a test to stop this regressing, but PRing without a test for feedback.
/cc @titanous
=> client: Always initialize keys DB from local storage

client/interop_test.go, data/types.go, keys/db.go, local_store.go, repo.go, repo_test.go, signed/keys.go, signed/sign.go, signed/verifiers.go, signed/verify.go, signed/verify_test.go
This is the first step towards supporting ECDSA keys and signing via PKCS11.
- Remove unused RSA signature verifier.
- Use `golang.org/x/crypto/ed25519` package instead of `github.com/agl/ed25519`.
- Don't mix private and public key structs, use a separate struct
for private keys.
- Only store public keys in database used for signature
verification.
- Use `crypto.Signer` interface instead of providing private keys
directly when signing.
- Don't make as many assumptions about using Ed25519 keys
everywhere.
- Ignore unknown key types when populating the public key database.
I've tested that keys generated with the previous implementation can be decoded and used by this refactored code (there is no change in the serialized data structures).
=> Refactor key handling

data/types.go, verify/verifiers.go, verify/verify.go, verify/verify_test.go
- verify: Don't assume signature method, use key type
It is unsafe to use the signature method field, as it could result in a key confusion attack. Use the key type instead.
Also, don't assume that we're only working with Ed25519.
-  	verify: Add support for `ecdsa-sha2-p256` signatures
=> ECDSA verification support

repo.go
Useful for checking if targets exist before adding them.
=> repo: Add Repo.Targets

encrypted/encrypted_test.go
If we get really unlucky the encrypted bytes already start with 0x0000
so the tampering fails.
Signed-off-by: Dan Johnson <computerdruid@google.com>
=> encrypted: fix flake in EncryptedSuite.TestTamperedRoundtrip

cmd/tuf/gen_key.go
Hi @erickt and @trishankatdatadog,
This is my first 'real' PR. While playing around with tuf locally to get warm with it, I found this small
issue in the `tuf` command line tool.
You can reproduce this issue via:
```
$ go get github.com/theupdateframework/go-tuf/cmd/tuf
$ mkdir tuf-demo
$ cd tuf-demo
$ tuf init
$ tuf gen-key --expires=30 INVALID
```
With the current master the command will return exit code 0 and will not display any error code.
With my PR applied we get the correct result and `tuf gen-key --expires=30 INVALID` returns an error.
More details can be found in the commit message
=> fix wrong error state with tuf gen-key

client/client.go, client/client_test.go, data/types_test.go, repo.go, repo_test.go
In [TAP-12], we're considering removing the requirement that keyids are derived using `hexdigest(sha256(cjson(public_key_data)))`. This patch updates go-tuf to ignore, rather than fail out, if we see a keyid that wasn't derived with this algorithm. This makes us both forward compatible to TUF-1.0, and backwards-compatible with go-tuf's hybrid 0.9/1.0 transition.
Test: Added tests that make sure repos can generate new versions of metadata and preserve unknown keyids, and that clients ignore repos with random string keyids.
[TAP-12]: https://github.com/theupdateframework/taps/blob/master/tap12.md
=> Ignore unknown keyids

README.md, cmd/tuf/get_threshold.go, cmd/tuf/main.go, cmd/tuf/set_threshold.go, repo.go, repo_test.go
Adds the ability to modify role thresholds in the CLI
Fixes https://github.com/theupdateframework/go-tuf/issues/6
Question: are there CLI tests? 
=> Support modifying role thresholds

local_store.go, repo.go
In order to implement a custom LocalStore, you will need to reference targetsWalkFunc, which is currently private. Make this public so custom LocalStores can be implemented in external libraries.
=> Make targetsWalkFunc public

repo.go, repo_test.go
Allows users to sign content with an external tool. Required
* Making `SignedMeta` public to access the signable content as the payload to sign
* AppendSignature: adds a signature to the metadata. Checks that this is a valid key for the role and replaces existing sigs with the same ID
* Adding a method to add a verification key, similar to the python reference implementation. This adds the public key data for a role to the root metadata without needing the private key
=> Add the ability to sign with an external tool (Dump signable content + append signature)

README.md, client/client_test.go, client/python_interop/python_interop_test.go, client/testdata/go-tuf-transition-M3/generate.go, client/testdata/go-tuf-transition-M4/generate.go, client/testdata/go-tuf/generator/generator.go, cmd/tuf/snapshot.go, repo.go, repo_test.go
The following PR removes the `--compression` option when creating a snapshot. It also updates the related tests and the README.md file. 
This change is a result of [TAP10](https://github.com/theupdateframework/taps/blob/master/tap10.md).
Closes issue #7 as it's no longer applicable.
=> Remove the --compression option when creating snapshots, ref. TAP10

.gitignore, README.md, cmd/tuf/add.go, cmd/tuf/clean.go, cmd/tuf/gen_key.go, cmd/tuf/main.go, cmd/tuf/regenerate.go, cmd/tuf/remove.go, cmd/tuf/sign.go, cmd/tuf/snapshot.go, cmd/tuf/timestamp.go, repo.go
The following PR updates the descriptions we provide for the CLI options along with some additional housekeeping.
Details:
- Added `.gitignore` file for ignoring `tuf` and `tuf-client` executables
- Added entry for `init` in the `tuf help` message
- Added documentation about the use of environment variables for passing each role's passphrases -`TUF_{{ROLE}}_PASSPHRASE` closing #73 
- Added documentation for `revoke-key` in README.md - closing #85 
- Added a "not-supported-yet" status for the `regenerate` command as it's still not implemented
- Updated the info for the `sign` command in the README.md file - it expects a role metadata filename (i.e. targets.json) instead of just the name of the role
=> Update CLI descriptions and their reference in the README.md file

client/client.go, client/delegations_test.go
When using delegations, a specific target file should be search among all the delegations targets
=> Look for target in delegations

client/client.go, client/client_test.go
For partial verification, we should be able to update the root without needing the update of the non-root metadata. 
This is because in many implementations of the partial verification, there is no timestamp or snapshot so a general update will fail.
=> make the updateRoots public

README.md, cmd/tuf/add.go, cmd/tuf/clean.go, cmd/tuf/gen_key.go, cmd/tuf/main.go, cmd/tuf/regenerate.go, cmd/tuf/remove.go, cmd/tuf/revoke_key.go, cmd/tuf/sign.go, cmd/tuf/snapshot.go, cmd/tuf/timestamp.go, local_store.go, repo.go
The following PR renames the use of `manifest` to `metadata` so the implementation is consistent with what is used within the TUF specification.
=> Rename manifest to metadata for consistency with the TUF specification

data/types.go, data/types_test.go
We are looking to add custom metadata to `root` and `targets` roles. I'm also adding the same custom filed to `snapshot` and `timestamp` to align all the roles nicely.
Relevant entry in the specification: 
> 4. Document formats
>All of the formats described below include the ability to add more attribute-value fields to objects for backwards-compatible format changes. Implementers who encounter undefined attribute-value pairs in the format must include the data when calculating hashes or verifying signatures and must preserve the data when re-serializing. If a backwards incompatible format change is needed, a new filename can be used.
https://theupdateframework.github.io/specification/latest/#document-formats
=> add custom fields to all top level roles

repo.go, repo_test.go
As noted in issue https://github.com/theupdateframework/go-tuf/issues/167, when a key that is used between multiple roles (e.g. roleA and roleB) is revoked from roleA, the key is still deleted from `root.Keys`, so roleB is left in a bad state where its key is not present in root.Keys.
This fixes that by only deleting the key from `root.Keys` if NO role is using the key anymore. Added a test that would previously fail.
=> bugfix: Fix key revocation when key is shared between roles

README.md, cmd/tuf/get_threshold.go, cmd/tuf/main.go, cmd/tuf/root_keys.go, cmd/tuf/set_threshold.go, repo.go
The following PR adds informative messages about each CLI command upon successful completion. Closes #11 
One thing I'd like to note is the output for `tuf root-keys` previously consisted only of the JSON encoded root keys and now there's a helpful message before that. This might break stuff in case there's some automation built around it, so let me know if it might make sense to revert that change specifically. 
Examples of the resulting output:
```bash
./tuf init
Repository initialized
------------
./tuf gen-key root
Enter root keys passphrase: 
Repeat root keys passphrase: 
Generated root key with ID 157a50daaa57d68518ea1a47190e9ffd4be1985647f320409fa28d8c07b1ab6a
------------
./tuf revoke-key root a94ce6fd989d04d5d86202a80b320b3ab1ae60d44c693aad41be76ab5e6f568c
Revoked root key with …
```
=> Improve the CLI experience

MAINTAINERS
I propose Ethan Lowman as a maintainer considering his active contributions.
=> Propose Ethan Lowman

.gitignore, README.md, cmd/tuf/change_passphrase.go, cmd/tuf/main.go, errors.go, local_store.go, repo.go, repo_test.go, util/util.go
The following PR adds support for changing the passphrase for a given role keys file. 
Closes #60 
The format of the command is `tuf change-passphrase <role>`. Example usage:
* In case the keys file exist - 
```bash
tuf change-passphrase root
Enter root keys passphrase: 
Enter new root keys passphrase: 
Repeat new root keys passphrase: 
Successfully changed passphrase for root keys file
```
* In case the keys file doesn't exist yet - 
```bash
tuf change-passphrase snapshot
Failed to change passphrase. Missing keys file for snapshot role. 
ERROR: open <path>/go-tuf/cmd/tuf/keys/snapshot.json: no such file or directory
```
=> Add support for changing keys file passphrase

client/leveldbstore/leveldbstore.go
This can help avoid subtle memory leaks
=> always close both `db` and `fd` in `Close()`

client/client.go, client/leveldbstore/leveldbstore_test.go, client/local_store.go, client/local_store_test.go
This allows for package consumers to elegantly`Close()` the underlying datastore, avoiding memory leaks.
See also: https://github.com/sigstore/cosign/issues/1160
=> expose `Close()` in `LocalStore` interface

internal/targets/hash_bins.go, internal/targets/hash_bins_test.go
This PR adds helpers to support hash bin targets delegation. The helpers will be used to generate a list of hash bin manifest names as `leaf_00.json, leaf_01.json, leaf_02.json, ..., leaf_ff.json`, which a targets manifest such as `bins.json` may delegate to using the TUF `path_hash_prefixes` feature ([see spec](https://theupdateframework.github.io/specification/latest/#path_hash_prefixes)).
=> [Delegations prereq 2] Add hash bins helpers

internal/roles/roles.go, internal/roles/roles_test.go, repo.go, verify/db.go, verify/verify.go
Adds helpers such as `IsTopLevelRole` and `IsDelegatedTargetsRole`, which help make conditionals on role names/manifest names more readable.
=> [Delegations prereq 3] Add roles helpers

data/types.go, repo.go
This was originally reviewed in #195, but the stacked PR was accidentally merged out of order.
=> [Delegations prereq 5, reopened] Support delegated targets in DefaultExpires and fix GenKey expiration

client/client.go, client/client_test.go, repo.go, repo_test.go
Allows users of go-tuf to sign oci images or other non-local targets by directly providing the hash and length of these artifacts. Solves #165
cc @ethan-lowman-dd @trishankatdatadog @sudo-bmitch
=> Add digest to targets metadata directly

pkg/keys/ed25519.go
1. Makes `Ed25519PrivateKeyValue` public
2. Adds a way to instantiate ed25519Signer from `Ed25519PrivateKeyValue`
With the change of interface for the keys there is no non-hacky way to use an ed25519 key that is not stored as a `go-tuf` specific marshaled JSON blob without re-implementing the signer interface.
=> make ED25519PrivateKeyValue public, add a way to instantiate ed25519Signer from it

client/client.go, client/client_test.go, client/delegations_test.go, client/interop_test.go, client/python_interop/python_interop_test.go, cmd/tuf-client/init.go
This will allow users of go-tuf to initialize a client
without requiring a remote connection. This is useful
for when a root has been updated and the local root
verification keys can no longer verify the the latest
remote root, except by verifying the chain with
client.Update().
Ref #208
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>
=> Add client method for initializing from root metadata

client/testdata/go-tuf-transition-M3/generate.go, client/testdata/go-tuf-transition-M4/generate.go, client/testdata/go-tuf/generator/generator.go, client/testdata/tools/gen-keys.go
The `assertNotNil` helper functions were actually asserting that the error *was* nil. This PR renames the functions to reflect their actual behavior.
=> Rename assertNotNil to assertNoError, since the former name is incorrect

client/delegations.go, client/delegations_test.go, pkg/targets/delegation.go, pkg/targets/delegation_test.go, verify/db.go, verify/db_test.go
This PR removes the type `verify.DelegationsVerifier` in favor of using a `verify.DB` directly to store sets of keys. This simplifies the types, since a `DelegationsVerifier` just wrapped a `DB` without adding significant functionality, and allows us to use the same type (a `verify.DB`) to hold keys for the top level targets role as for delegated targets roles.
=> [Delegations prereq 6] Use a verify.DB for delegation in client

repo.go, repo_test.go
By making `init` write an empty `targets.json`.
The following didn't work before but now does:
```shell
tuf init
tuf gen-key root
tuf gen-key targets
tuf gen-key snapshot
tuf gen-key timestamp
tuf sign root.json
tuf sign targets.json
tuf snapshot
tuf timestamp
tuf commit
```
=> Allow commit without adding targets

errors.go, repo.go, repo_test.go
Leads to better error messages throughout. Also improve repo_test
coverage to exercise all of the ErrInvalidKeys paths.
=> Add Reason to ErrInvalidKeys

local_store.go, repo_test.go, verify/db_test.go
This is a small PR separating a few fixes for linter errors that would otherwise be raised by golangci-lint/staticcheck in #234. 
=> Fix linter errors raised by staticcheck

.github/workflows/release.yml
Exposing the OIDC token is not necessary until we decide to use an OIDC issuer for signing.
Relates to https://github.com/theupdateframework/go-tuf/pull/234
=> chore: remove exposing the github oidc token in ci

.github/workflows/tests.yml
Release Notes: Bump golangci-lint to 1.45.2
Attempts to fix panic in golangci-lint (example: https://github.com/theupdateframework/go-tuf/runs/5889222812?check_suite_focus=true)
Related: https://github.com/golangci/golangci-lint/issues/2374, https://github.com/golangci/golangci-lint/issues/2649
=> ci: Bump golangci-lint to 1.45.2

client/client.go, client/client_test.go, client/delegations_test.go, client/errors.go, data/types.go, local_store.go, repo.go, repo_test.go, util/util.go, util/util_test.go, verify/errors.go, verify/verify.go, verify/verify_test.go
Release Notes: Metadata version now uses int64
We have a high write throughput on our TUF repositories and there's a good chance we'll reach 2B+ snapshots versions in the future which would break our clients on 32bit archs. Let's standardize to `int64` to avoid any surprises.
=> use int64 instead of int for metadata version

.github/workflows/changelog.yml, .github/workflows/tests.yml
Release Notes: PR titles must now use [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format
One of the effects of https://github.com/theupdateframework/go-tuf/pull/234 is that we have to format every commit message using the Conventional Commit format, even though we squash merge PRs, and that commit history is lost. Since the PR title (or in some cases a single commit message) becomes the squashed commit message, that is the place we should check for …
=> ci: Check PR title instead of commits for conventional format

client/errors.go, errors.go, local_store.go, repo.go, repo_test.go, verify/db.go
This pr is a takeover of #171, which I don't seem to be able to edit directly.
cc @ethan-lowman-dd @asraa @trishankatdatadog @hosseinsia
=> feat: Support delegated targets roles in repo writer

.github/workflows/tests.yml
We've been seeing test failures: https://github.com/theupdateframework/go-tuf/runs/6215906951?check_suite_focus=true
See: https://github.com/golangci/golangci-lint-action/issues/297
Fixes N/A
Release Notes: N/A
- [-] Tests have been added for the bug fix or new feature
- [-] Docs have been added for the bug fix or new feature
=> chore: bump golangci-lint timeout

.github/workflows/release.yml, .github/workflows/tests.yml
Hi,
I'm the author of [arnested/go-version-action](https://github.com/marketplace/actions/go-version-action).
The action doesn't need a GITHUB_TOKEN anymore.
Instead of getting the Go releases from git tags using GitHub's API (and thus needing the token to avoid being rate limited) it pulls the versions from https://go.dev/dl/?mode=json&include=all.
=> chore: remove GITHUB_TOKEN from arnested/go-version-action 

.github/workflows/specification-version-check.yml, docs/MAINTAINERS.md
Fixes #283
The following PR adds a workflow that keeps track and creates an issue for notifying of new TUF specification releases. 
For the time being, there's no decision on stating the version of the TUF specification which go-tuf complies with. Until this is addressed, the version of the spec which will be used for the verification is added manually. 
**Note:** Dependent on - https://github.com/theupdateframework/specification/pull/224
**Please verify and check that the pull request fulfills the following …
=> feat: add workflow responsible for notifying of new TUF spec release

docs/CONTRIBUTING.md
=> docs: Add DCO instructions

client/client.go, docs/CONTRIBUTING.md, repo.go, verify/db.go, verify/db_test.go, verify/errors.go
Fixes #232
Release Notes: Add support for repositories that implement TAP-12 (allowing arbitrary key IDs). go-tuf itself will continue to emit pre-TAP-12-compliant key IDs.
Allows arbitrary key IDs in repos that we read, per [TAP-12](https://github.com/theupdateframework/taps/blob/master/tap12.md). (We will still only produce key IDs that are the SHA2 of the public key.)
=> feat: Implement TAP-12 support

.github/workflows/tests.yml
=> chore(deps): bump Python from 3.6 to 3.10

client/client.go, util/util.go, util/util_test.go
Fixes #233
Check hashes and length of downloaded snapshot and targets metadata before parsing.
Better match the specification by performing checks against length and hashes on the downloaded bytes before parsing the bytes into a FileMeta.
=> fix: verify length and hashes of fetched bytes before parsing

docs/MAINTAINERS.md
Fixes #335 
Release Notes: N/A
This proposes a "cut a patch version at any time, but give everyone a 24hr heads-up in case there are objections" policy. I think this is fine because we maintain a green HEAD at all times, but I'm open to other suggestions (though preference is to keep the process lightweight for patch versions).
CC all maintainers since this affects process: @rdimitrov @asraa @joshuagl @mnm678 @trishankatdatadog @ethan-lowman-dd @hosseinsia
=> docs: Add release process info for maintainers

README.md
Signed-off-by: Andrés Torres <andrest@vmware.com>
Fixes #<Issue>
Remove typo in _Alternate signing flow_ section of README. Running the current command was returning:
```
tuff add-signatures --signatures=root.json.sigs root.json
--signatures must not have an argument
```
With the suggestion, the command works as expected:
```
tuf add-signatures --signatures root.json.sigs root.json
tuf: added 1 new …
```
=> fix: Remove typo in Alternate signing flow

cmd/tuf/main.go
Signed-off-by: Andrés Torres <andrest@vmware.com>
Fixes #<Issue>
Redirect passphrase output to Standard error so that we can pipe the output of commands requiring passphrases. See https://github.com/theupdateframework/go-tuf/pull/160#issuecomment-937711887 and https://cloud-native.slack.com/archives/C02D577GX54/p1657742840578189
**Please verify and check that the pull request fulfills the following …
=> fix: Redirect passphrase output to Standard error

client/client.go, data/types.go, repo.go, repo_test.go, util/util.go, util/util_test.go
Fixes #<Issue>
```
* breaking change: `data.FileMeta` no longer contains a `Custom` field
```
Rust's `tough` requires length in the JSON, and go-tuf omits if empty. always marshal a length, even if `0`. Some files need to be signed as empty because there is explicitly no content there.
cc @raulcabello
- [ x ] Bug fix (non-breaking change which fixes an issue) …
=> fix: require length and hashes for target metadata

client/leveldbstore/leveldbstore.go, client/leveldbstore/leveldbstore_test.go
While fixing #349, the leveldb supports a Recover() method in case the
manifest is broken. I validated that the Recover would have recovered
the manifest file using the db file (that still existed). Add a test
that validates if the manifest is truncated, it can be recovered.
Signed-off-by: Mike Marchetti <mike@agilicus.com>
Fixes #<Issue>
**Please verify and check that the pull request fulfills the following …
=> fix: add leveldb recover ability

client/client.go, client/client_test.go, client/delegations_test.go, client/interop_test.go, client/python_interop/python_interop_test.go, cmd/tuf-client/init.go
Straightforward find/replace:
find . -name '*.go' | xargs sed -i 's/InitLocal/Init/g'
BREAKING CHANGE: the method signature of `Init()` has changed since the
last release to take in the raw `root.json` metadata.
Fixes #208
Release Notes: the method signature of `Init()` has changed since the
last release to take in the raw `root.json` metadata.
**Description of the changes being introduced by the pull request**: rename "InitLocal" to "Init"
=> refactor!: rename "InitLocal" to "Init"

client/client_test.go, verify/verify.go
Release Notes: Fixes a vulnerability in the verification of threshold signatures (due to handling of keys with multiple IDs)
Go-TUF has a security vulnerability in the way it validates threshold signatures: it relies on the key IDs declared in the metadata file it is currently validating (varibale `sig.KeyID`) to tell if this new signature should count towards the threshold, assuming that these IDs will be the same as the one it generates (`verifier.MarshalPublicKey().IDs()`). This assumption can be made false and this can be leveraged to forge valid threshold signatures using a number of keys which, in theory, should be insufficient.
This PR adds a test demonstrating the vulnerability, then it …
=> fix(verify):  Fix a vulnerability in the verification of threshold signatures (due to handling of keys with multiple IDs)

.github/workflows/tests.yml, .golangci.yml, client/client.go, client/client_test.go, client/delegations_test.go, client/interop_test.go, client/python_interop/python_interop_test.go, client/testdata/go-tuf-transition-M3/generate.go, client/testdata/go-tuf-transition-M4/generate.go, client/testdata/go-tuf/generator/generator.go, client/testdata/tools/gen-keys.go, client/testdata/tools/linkify-metadata.go, cmd/tuf-client/get.go, local_store.go, repo_test.go, util/util.go, verify/db_test.go
Fixes #362
Release Notes:
- Use Go 1.17 for golangci linting until generics are supported.
- Update golangci/golangci-lint-action and run checks using the correct version of Go for the Go version matrix.
Go 1.18 is not supported by golangci-lint yet since generics are not supported. To fix, we have to lint using Go 1.17. Note that gofmt checks still appear to target the latest Go version.
=> build: Use Go 1.17 for golangci linting and update golangci/golangci-lint-action

cmd/tuf/gen_key.go, data/types.go, go.mod, internal/signer/sort_test.go, pkg/deprecated/deprecated_repo_test.go, pkg/deprecated/set_ecdsa/set_ecdsa.go, pkg/keys/deprecated_ecdsa.go, pkg/keys/deprecated_ecdsa_test.go, pkg/keys/ecdsa.go, pkg/keys/ecdsa_test.go, pkg/keys/ed25519.go, pkg/keys/keys_test.go, pkg/keys/pkix.go, pkg/keys/pkix_test.go, pkg/keys/rsa.go, pkg/keys/rsa_test.go, repo.go, repo_test.go, verify/db.go, verify/verify_test.go
Fixes https://github.com/theupdateframework/go-tuf/issues/223
* breaking change: ECDSA public key verification now use TUF compliant PEM-encoding keys. For backwards compatibility with hex-encoded keys verification, client libraries must import `pkg/deprecated`
* feat: Adds support for ECDSA and RSA signers 
* feat: Repository CLI command allows a `--scheme` flag to specify key scheme.
* Defined new go types for KeyType, KeyScheme and HashAlgorithm, rather than just using strings, and fixed a few places where the key type and scheme had been mixed up.
* Added a new …
=> feat: Support ecdsa and RSA keys (#270 with backwards compatibility)

client/client.go, client/client_test.go
Adds a new test for this case: if a client sees a new `timestamp.json` file with the same version as its current `timestamp.json` file, it should do nothing (no update, but also no error).
A few other tests were implicitly relying on the fact that the client did a full update each time, so they've been updated to commit a new timestamp.
This updates go-tuf for TUF specification v1.0.30 (fixes #321). The only substantive change was
[theupdateframework/specification#209][tuf-spec-209], which clarifies the intended behavior for updating metadata files.
Updates for other roles were already in compliance:
- Root metadata: https://github.com/theupdateframework/go-tuf/blob/13eff30efd6c61f165e1bf06e8c0e72f5a0e5703/client/client.go#L258
- Timestamp, checking snapshot version: …
=> fix: abandon updates if timestamp.json isn't new

README.md
Fixes #285
documentation change
Documents root key addition and rotation
=> docs: Add docs for adding and rotating root keys

.github/workflows/tests.yml
Context: linting in CI (`golangci-lint`) occasionally times out on
Windows (flaky). Most of the time, it's fast enough (~1min). But
occasionally it hits the 3 minute timeout. It's somewhat expected that
`golangci-lint` is slow:
https://github.com/golangci/golangci-lint-action/issues/297
This PR does 3 things:
1. Bump the timeout from 3 to 5 minutes (why solve the problem when you
can band-aid it?)
2. Add the `--verbose` flag, so if we start to see this again we'll have
much better information with which to figure out what specifically is
taking so long.
3. Remove the patch number from the `golangci-lint` version; it's
disallowed, according to the `golangci-lint` action README.
Fixes https://github.com/theupdateframework/go-tuf/issues/390 (for …
=> test: update lint CI parameters

cmd/tuf-client/main.go, cmd/tuf/main.go
Fixes comments of https://github.com/theupdateframework/go-tuf/pull/385
```
* fix(cmd): Prints help message on `Stdout` rather than `Stderr`
```
Fixes #<Issue>
=> fix(cmd): fix logging of help message

.github/workflows/tests.yml
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
Fixes #<Issue>
Currently if a single test leg fails all the legs are immediately failed. This makes testing a bit cumbersome because it would be better to see all the failures at once rather than whack a mole. This is especially troublesome when the tests run on a machine that I do not have access to in order test that platform.
=> test: Do not fail-fast when CI runs.

client/client.go, client/client_test.go, client/file_store.go, client/file_store_test.go
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
Fixes #<Issue>
Release Notes:
* Add file_store that implements RemoteStore backed by https://pkg.go.dev/io/fs. This is handy if you want to run airgap and bring your own repo.
- [ x ] New feature (non-breaking change which adds functionality)
Add Filesystem based remote store that the client can use. Motivation is to support airgapped environments which can't make network calls. The interface is golang io/fs.FS so that it can be backed by anything that supports the interface instead of only relying on disk.
I may have missed something, but I …
=> feat: Add Filesystem based remote store to support airgap.

docs/SECURITY.md
Fixes https://github.com/theupdateframework/go-tuf/issues/371
=> docs: add security.md

docs/MAINTAINERS
Fixes #<Issue>
Removing myself as a maintainer since I no longer have adequate time available.
=> docs: Remove ethan-lowman-dd from maintainers

docs/MAINTAINERS
Remove @hosseinsia from list of maintainers. Thanks for your service!
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> docs: Update MAINTAINERS

docs/SECURITY.md
We can replace the Google form with Github's new vulnerability reporting feature! This will ensure that the set of folks who receive reports automatically syncs with current maintainers. More information about this feature is available [here](https://github.blog/changelog/2022-11-09-privately-report-vulnerabilities-to-repository-maintainers/).
This should only be merged after @joshuagl presses the button to enable this feature.
=> docs: Use Github's vulnerability reporting

.github/workflows/ci.yml
The following PR elevates the GitHub Token permissions for the release workflows.
Fixes #436 
=> chore: elevate GitHub token permissions for release.yml workflow

client/client_test.go
Fixes https://github.com/theupdateframework/go-tuf/issues/286
* client: adds testing for rollback protection on snapshot, targets, and delegated targets
Relevant: https://github.com/theupdateframework/go-tuf/issues/449
(Testing is already added for timestamp)
=> test: add tests for rollback protection on snapshot, targets, delegations

.github/workflows/tests.yml, .golangci.yml
The following PR fixes the CI issues around Go 1.20 by updating the version of golangci-lint. It also removes the unnecessary version pin in its config file. 
The reason this has to be done manually is Dependabot takes care of updating the action, but the golangci-lint version has to be manually pinned because of our testing scenarios. For reference - https://github.com/golangci/golangci-lint-action/blob/6a290f7d5d488e1e423b0b37fe802c822ca2c08c/README.md?plain=1#L108
Fixes #455
Related to #454 
**Please verify and check …
=> fix: golangci-lint failures when tested against Go 1.20

README.md
`go get` is deprecated
Fixes #<Issue>
=> docs: Update install instructions in README

.goreleaser/tuf-client.yml, .goreleaser/tuf.yml
Per #461. 
Note that I'm no build process expert, but I reckon this should work.  ;-)
=> ci(build): Add arm64 to build

cmd/tuf/sign_payload.go, repo.go, repo_test.go, sign/sign.go
- Add new `Repo.SignRaw` which doesn't canonicalize before signing (and just returns Signatures)
- Rename `SignPayload` to `CanonicalizeAndSign` (old name is deprecated; it probably doesn't actually get used so we can rip out next major release.)
- Add `sign.MakeSignatures` which does not canonicalize; refactor `sign.Sign` to use it.
- Modify offline flow to test this property.
- Use `SignRaw` in `tuf sign-payload`.
Fixes #475.
Release Notes:
- (API) `Repo.SignPayload` is deprecated; please use `CanonicalizeAndSign` instead.
- (CLI) Fix `tuf sign-payload` to not re-canonicalize the input. …
=> fix: sign-payload shouldn't recanonicalize payload

.github/dependabot.yml
Disable daily checking for version but not security updates.
Maybe we should also document a process for version updates when cutting a new release?
=> ci: Disable daily checking for version but not security updates

encrypted/encrypted.go, encrypted/encrypted_test.go
Fixes #467
Increase the default `scrypt` KDF parameters to a more recent parameter set. 
Provides backward compatibility to for legacy parameter set, and provides more recent parameter based on various recommendations (Scrypt Author / OWASP).
- `Legacy` settings (2^15, 8, 1)
- `Standard` recommended settings (2^16, 8, 1) => Targeting ~100ms
- `OWASP` recommended settings (2^17, 8, 1)
=> feat: increase scrypt parameters

README.md
Solves #128
It might be nice to clarify what implementations there are in other languages, but I couldn't find an active list of all the TUF implementations and don't think that this is the place to maintain that.
=> docs: add list with alternative implementations

README.md, cmd/tuf/add_key.go, cmd/tuf/main.go, pkg/keys/rsa.go, pkg/keys/rsa_test.go, repo.go
Fixes #528 
Release Notes: Introduces the `add-key` command
Introduces the `add-key` command
=> feat: #528 Add-Key to a role

README.md, cmd/tuf/add_signatures.go
Fixes #529 
Release Notes: add-signature to read from stdin
- [ x] New feature (non-breaking change which adds functionality)
add-signature to read from stdin
=> fix: add-signature to read from stdin

README.md
The following PR fixes the CI status badge and updates the README.md file with a status update on the migration process.
Thanks to @HLeithner for bringing this up 💯 
Related to https://github.com/theupdateframework/go-tuf/issues/485
=> chore: fixes the CI status badge and updates the README.md file

docs/MAINTAINERS
The following PR updates my employer email and adds Marvin Drees (@MDr164) to the list of go-tuf maintainers!  🎉
=> docs: add Marvin Drees to the list of go-tuf maintainers

.github/dependabot.yml, .github/workflows/auto-merge.yml
Enable automerge.
Fixes #<Issue>
=> chore: enable grouping of minor and patch updates.

.github/workflows/tests.yml
Fixes the issues we observe with go 1.21. 
Reference: https://github.com/golangci/golangci-lint/issues/3933
=> fix: update tests.yml bumping golangci-lint

.github/workflows/tests.yml, examples/cli/tuf-client/cmd/get.go, examples/cli/tuf-client/cmd/init.go, metadata/metadata_api_test.go, metadata/metadata_test.go, metadata/trustedmetadata/trustedmetadata_test.go, metadata/updater/updater.go, metadata/updater/updater_consistent_snapshot_test.go, metadata/updater/updater_top_level_update_test.go, testutils/simulator/repository_simulator.go, testutils/simulator/repository_simulator_setup.go, testutils/testutils/setup.go
Since windows tests were disabled, it looks like we've drifted a bit and introduced a few issues preventing the tests from passing and from the project working on windows:
* use of unix path separators throughout
* tests relying on line endings, and Git checkouts being different for windows/linux
* renaming of files between drives on windows on GitHub Actions
* renaming of open files (not allowed on windows)
Moved from https://github.com/rdimitrov/go-tuf-metadata/pull/98
*EDIT*
* Maybe merge this one first so that this PR can be tested properly: https://github.com/theupdateframework/go-tuf/pull/587
=> Fixes for windows & enable in CI

SECURITY.md
Copy back previous Security Policy at:
https://github.com/theupdateframework/go-tuf/blob/32712b6d3c14b39aee99c35e5cbb6a519ae49e5b/docs/SECURITY.md
=> Bring back SECURITY.md

metadata/errors.go, metadata/fetcher/fetcher.go, metadata/fetcher/fetcher_test.go, metadata/marshal.go, metadata/metadata.go, metadata/metadata_api_test.go, metadata/trustedmetadata/trustedmetadata.go, metadata/trustedmetadata/trustedmetadata_test.go, metadata/updater/updater.go, metadata/updater/updater_top_level_update_test.go, testutils/simulator/repository_simulator.go
This PR changes all errors to use pointer receivers, as is common Go idiom.
This doesn't change any behavior. It started as my attempt to fix something I thought was a bug, but I think I misunderstood. I won't feel bad if you decide to close/reject as this doesn't change any behavior and introduces a lot of LoC changes.
Pointer receivers have some benefits for use in error handling -- notably you can compare errors to nil (`if err == nil` vs `if err == MyError{}`). The choice is somewhat arbitrary, but using pointers is far more conventional.
=> Refactor errors to use pointer receivers

.github/workflows/examples.yml, .github/workflows/tests.yml, metadata/fetcher/fetcher.go
The following PR enables both `macos-latest` and `windows-latest` runner environments for the actions running the tests and the examples.
=> Enable macos and windows runners for examples.yml and tests.yml

metadata/updater/updater.go
Partly fixes https://github.com/theupdateframework/go-tuf/issues/605
The `example-root-signing` test should now work on Windows.
=> Use filepath.Join when combining filesystem components

examples/multirepo/client/client_example.go
Even when running on Windows, the targets in the root uses forward slash.
Closes https://github.com/theupdateframework/go-tuf/issues/605
=> Always use forward slash when splitting target names

.github/workflows/linting.yml
As we only pin the minor version and not the patch version of Go (as most projects do), we can't guarantee the CI to use a toolchain version which has security fixes govulncheck would otherwise complain about.
EDIT: We keep the go.mod as is but modified the CI pipeline as outlined below.
=> Silence govulncheck

go.mod, go.sum, internal/testutils/simulator/repository_simulator.go, internal/testutils/simulator/repository_simulator_setup.go, metadata/updater/updater_top_level_update_test.go
=> feat: replace logrus in sim with slog

internal/testutils/simulator/repository_simulator_setup.go
Per title.
e.g. `tmpDir + metadataPath` is just weird and fragile, use `filepath.Join()`, its what its there for.  :wink:
=> repository_simulator_setup.go: Use filepath.Join() instead of concatenation

metadata/updater/updater.go
When go-tuf is unable to persist the TUF metadata, I receive the error "failed to persist metadata: %!w(\<nil\>)". Because the code already checks if the error is not nil and returns it if not on [line 651](https://github.com/theupdateframework/go-tuf/blob/b2e024ad4752cc0c4a4e376460b21deb79e40ded/metadata/updater/updater.go#L651), the "failed to persist" error message will always try to print a nil error.
=> Remove nil error from being printed in "persist metadata" error message

metadata/updater/updater.go, metadata/updater/updater_top_level_update_test.go
This PR exports an API to set the `RefTime` of the trusted metadata of an `Updater`. This is useful for testing time-related cases in the client outside of go-tufs own repository.
=> export API to set RefTime of Updater

metadata/config/config.go, metadata/config/config_test.go
The default value of 32 is quite small, it may break certain clients that are trying to do complete tuf refresh on a large TUF repo.
Closes #644
=> Increase the default value for MaxRootRotations

metadata/updater/updater.go
The following PR fixes the issue where go-tuf will SIGSEGV if a top-level target delegates to another role but that role is not listed in the snapshot metadata.
This is highly unlikely to happen because the attacker must have the ability to create a delegation to a new role in the repository and must be able to prevent this delegation from being included in snapshot metadata in the repository. This implies a significant compromise of a repository. If these requirements are met and client tries to download anything delegated to the new role, it will segfault. In any case it's worth fixing it.
Thanks to @jku for reporting this issue! 👏
=> Error in case the delegated role is missing from the snapshot

metadata/multirepo/multirepo.go
This PR prevent potential panic on NIL pointer when we trying to download file (from user input repo name for example).
=> fix: multirepo potential nil pointer dereference

examples/repository/basic_repository.go, internal/testutils/repository_data/repository/metadata/root.json, internal/testutils/repository_data/repository/metadata/snapshot.json, internal/testutils/repository_data/repository/metadata/targets.json, internal/testutils/repository_data/repository/metadata/timestamp.json, internal/testutils/rsapss/signer.go, internal/testutils/signer/signer.go, metadata/metadata.go, metadata/metadata_api_test.go, metadata/trustedmetadata/trustedmetadata_test.go
The following PR fixes an issue with go-tuf's support for RSA key types.
**Details:**
Apparently for RSA key types `signature.LoadVerifier()` is defaulting to returning a verifier that is `RSAPKCS1v15Verifier` which corresponds to the RSA PKCS#1 scheme. 
Based on [the latest TUF spec](https://theupdateframework.github.io/specification/latest/#file-formats-keys), TUF uses RSA PSS instead of PKCS#1. This manifests itself by causing go-tuf v2 TUF clients to fail metadata verification in case of RSA key types.
The fix for this is to invoke the proper verifier for the PSS scheme. This means that when we are verifying a metadata signed by an RSA key type, we should use `LoadRSAPSSVerifier()` instead of the generic `LoadVerifier()`.
**References:**
* …
=> Use the correct verifier for RSA PSS scheme keys

metadata/updater/updater.go
Ref https://github.com/theupdateframework/go-tuf/issues/667
I also added an explicit `file.Close()` on the error conditions here because otherwise `defer file.Close()` would be called after the `file.Remove()`, IIRC Windows errors if you attempt to remove an open file.
=> updater.go: replace os.WriteFile with file.Write()

examples/cli/tuf-client/cmd/init.go, examples/cli/tuf-client/cmd/root.go, examples/cli/tuf/cmd/root.go, metadata/metadata.go, metadata/updater/updater.go
propose removing `readFile()` from `updater.go` as it appears to essentially be a re-implementation of stdlib's `os.ReadFile`
Also found a "hidden" re-implementation of `os.ReadFile` in metadata.go, so changed that to `os.ReadFile` too.
Also found the re-implementation of `os.Readfile` in `cli/tuf/cmd/root.go`, so changed that to `os.ReadFile` too.
Also found a re-implementation of `os.ReadFile` in `cli/tuf-client/cmd/root.go` where it appears completely unused ?
Also `reverseSlice()` in `metadata/updater/updater.go` seems to be a reimplementation of stdlib's `slices.Reverse()` so removed that too.
Phew... I think that's all of them. 😆
=> Remove readFile() and reverseSlice() in favour of stdlib

metadata/updater/updater.go
=> updater.go: replace url.QueryEscape() with url.PathEscape()

internal/testutils/simulator/repository_simulator.go, metadata/fetcher/fetcher.go, metadata/fetcher/fetcher_test.go, metadata/updater/updater.go
The argument is documented as not used/deprecated.
=> Added back timeout to the fetcher DownloadFile method to avoid a breaking change.

metadata/fetcher/fetcher.go, metadata/fetcher/fetcher_test.go
If someone instantiates a new DefaultFetcher directly with `DefaultFetcher{}` instead of with the new constructor , `DownloadFile` will fail because the `client` field has not been set. This pull request updates `DownloadFile` to check if the `client` field is `nil` and sets a default HTTP client if it is to avoid breaking current usage of `DefaultFetcher`.
=> Set a default HTTP client for DefaultFetcher in DownloadFile method if none is set

metadata/updater/updater.go
Previously 403 was handled like 404 in the updater stating that no new update is available but that behavior is deemed incorrect in most cases so go-tuf will divert from python-tuf's behavior. This resolves #673
=> fix: treat http 403 as an updater error
