theupdateframework/go-tuf

- local_store.go
> Indent JSON files

- MAINTAINERS
I've already merged code that he's reviewed, better late than never :hear_no_evil:
> Add Eric to MAINTAINERS

- client/client.go
- client/client_test.go
- client/errors.go
- client/local_store.go
- local_store.go
- repo.go
- repo_test.go
- signed/verify.go
- util/util.go
- util/util_test.go
There are a couple of TODOs in here (i.e. handling invalid signatures, adding more tests) but I'll do them in supplemental PRs, I'm keen to get feedback on the implementation so far.
> Implement client.Update()

- repo.go
- repo_test.go
- signed/sign.go
> signed: Don't add duplicate signatures

- client/client.go
- client/client_test.go
- client/errors.go
> client: Improve errors

- client/client.go
- client/client_test.go
- client/errors.go
- util/util.go
An early stage PR to get feedback on the approach and for suggestions on appropriate tests to add.
> Implement Client.Download

- errors.go
- repo.go
- repo_test.go
- tuf/main.go
- tuf/revoke_key.go
> Support revoking keys

- client/client.go
- client/client_test.go
- client/errors.go
- signed/verify.go
- signed/verify_test.go
> client: Handle expired metadata

- client/client.go
- client/client_test.go
- client/errors.go
- repo.go
- signed/errors.go
- signed/verify.go
- signed/verify_test.go
This covers all TUF attack scenarios except "Slow Retrieval Attacks" (see #48).
Closes #28.
> Improve client tests

- client/client_test.go
- client/interop_test.go
- client/testdata/.gitignore
- client/testdata/LICENSE.txt
- client/testdata/client.py
- data/types.go
- local_store.go
- repo.go
- repo_test.go
Test compatibility with the Python client.
Closes #26.
> Test compatibility with the Python client

- client/interop_test.go
- encrypted/encrypted.go
- errors.go
- local_store.go
- repo_test.go
- tuf/main.go
- util/util.go
First part of #5 (the next part will be support for changing passphrases and enabling / disabling encryption)
> Support encrypting keys

- cmd/tuf/add.go
- data/types.go
- repo.go
> Add support for setting custom JSON with `tuf add`

- README.md
Signed-off-by: Vladimir Diaz <vladimir.v.diaz@gmail.com>
> Mention the '--expires' flag available to the 'tuf gen-key' command

- client/remote_store.go
This will be used like:
```go
opts := tuf.HTTPRemoteOptions{
UserAgent:          fmt.Sprintf("flynn-host/%s %s-%s %s", version.String(), runtime.GOOS, runtime.GOARCH, name),
ServerErrorRetries: tuf.DefaultServerErrorRetries,
}
```
> Support retrying HTTP requests for remote server errors

- cmd/tuf/main.go
This import is way more trouble than it's worth, so just remove the usage, which is very minor.
> cmd/tuf: Remove term package usage and import

- .travis.yml
- go.mod
- go.sum
> Use go mod

- local_store.go
> Fix panic when checking consistent snapshot paths

- data/types.go
This looks like it was typoed.
> Fix JSON struct tag for FileMeta

- .github/workflows/build.yml
- go.mod
- go.sum
Fixes https://github.com/theupdateframework/go-tuf/issues/178
> Upgrade to go 1.16

- repo.go
- repo_test.go
> [Delegations prereq 4] Clarify naming for top level targets, keys DB, and meta functions

- data/types.go
- repo.go
- repo_test.go
> [Delegations prereq 5] Support delegated targets in DefaultExpires and fix GenKey expiration

- repo.go
- repo_test.go
This was originally reviewed in https://github.com/theupdateframework/go-tuf/pull/194, but the stacked PR was accidentally merged out of order.
> [Delegations prereq 4, reopened] Clarify naming for top level targets, keys DB, and meta functions

- README.md
> Add dev/install requirements to README.

- MAINTAINERS
Fixes #<Issue>
- [N/A] Tests have been added for the bug fix or new feature
- [N/A] Docs have been added for the bug fix or new feature
> feat: propose adding Zach Newman to list of maintainers

- README.md
- docs/TESTING.md
- go.mod
- go.sum
Fixes https://github.com/theupdateframework/go-tuf/issues/307
Updates go version to 1.18.
Do we want to continue to test previous go versions?
- [ x ] Docs have been added for the bug fix or new feature
> build: update go version to 1.18

- util/util_test.go
Fixes #<Issue>
This catches a flakey test, where maybe the erroneous sha512 was picked up before sha256. 
For e.g. failed postsubmit here https://github.com/theupdateframework/go-tuf/runs/7137147768?check_suite_focus=true
> test: fix flakey util test

- .github/PULL_REQUEST_TEMPLATE.md
This drives me nuts every time :)
Fixes #<Issue>
> ci: Fix typo in Pull Request template

- .github/workflows/specification-version-check.yml
We fixed #321 but forgot to update this, so now the GH actions bot is confused (#391).
> chore: update TUF spec version

- .github/workflows/specification-version-check.yml
Fixes #391; see that issue for justification.
> chore: update TUF spec version to 1.0.31

- docs/TESTING.md
> docs: fix broken link

- .goreleaser/tuf.yml
> chore: update release notes breaking change regex

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #382
Signed-off-by: Zack Newman <zjn@chainguard.dev>
> docs: mention breaking changes in PR template

- .github/workflows/specification-version-check.yml
See #492 for justification. Fixes #494.
Release Notes: N/A
> chore: Bump spec version

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
Workflows are currently tied to 'main'
> Replace main with master in workflows

- metadata/fetcher/fetcher.go
To help with things like https://github.com/sigstore/sigstore-go/issues/143.
See https://github.com/sigstore/sigstore-go/pull/216 for an example of how this would be used.
> Add the ability to customize the HTTP user agent

- examples/multirepo/client/client_example.go
> Fix branch name in multi-repo client example

- MAINTAINERS.md
Retiring my maintainer role as I haven't been able to contribute or review changes in some time.
Keep up the great work!
> docs: Joshua retiring as a maintainer

- go.mod
> Bump Go to 1.22

- metadata/updater/updater.go
make function comment match function name
> chore: make function comment match function name
